import test from 'node:test';
import assert from 'node:assert/strict';
import { WezTermBackend,parsePanes,sendKeys,execute } from '../src/backend.js';
import { Agents,hashOutput,delta } from '../src/agents.js';
import { adapters } from '../src/adapters.js';
const pane={pane_id:7,tab_id:3,window_id:1,title:'test',cwd:'file:///tmp',size:{rows:24,cols:80}};
function fake(){let text='$ ',alive=true;const calls:any[]=[];const backend=new WezTermBackend(async(args,input)=>{calls.push({args,input});switch(args[0]){case 'list':return JSON.stringify(alive?[pane]:[]);case 'spawn':return '7\n';case 'get-text':return text;case 'kill-pane':alive=false;return '';default:return '';}});return {backend,calls,setText:(s:string)=>text=s,remove:()=>alive=false};}
test('parses real-shaped CLI JSON preserving extra metadata and rejects malformed IDs',()=>{assert.equal(parsePanes(JSON.stringify([pane]))[0].size.cols,80);for(const v of ['{}','oops',JSON.stringify([{...pane,pane_id:-1}])])assert.throws(()=>parsePanes(v));});
test('argv construction preserves commands literally, text travels through stdin',async()=>{const f=fake();await f.backend.spawn({cwd:'/tmp/a b',command:['echo','$(touch /tmp/nope)'],paneId:0});assert.deepEqual(f.calls[0].args,['spawn','--pane-id','0','--cwd','/tmp/a b','--','echo','$(touch /tmp/nope)']);await f.backend.sendText(7,'hello\nworld');assert.equal(f.calls[1].input,'hello\nworld');assert.equal(f.calls[1].args.includes('--no-paste'),false);});
test('validation prevents invalid IDs, NUL commands, conflicting spawn targets and unknown keys',async()=>{const f=fake();await assert.rejects(f.backend.read(-1));await assert.rejects(f.backend.spawn({command:['a\0b']}));await assert.rejects(f.backend.spawn({newWindow:true,windowId:1}));await assert.rejects(sendKeys(f.backend,7,['ENTER','BOGUS']));assert.equal(f.calls.length,0);});
test('raw key transport emits control bytes without bracketed paste',async()=>{const f=fake();await sendKeys(f.backend,7,['UP','CTRL_C','ENTER']);assert.deepEqual(f.calls.map(c=>c.input),['\x1b[A','\x03','\r']);assert.ok(f.calls.every(c=>c.args.includes('--no-paste')));});
test('hash and delta distinguish identical, appended and rewritten terminal output',()=>{assert.equal(hashOutput('a'),hashOutput('a'));assert.notEqual(hashOutput('a'),hashOutput('b'));assert.deepEqual(delta('a','ab'),{mode:'append',text:'b'});assert.equal(delta('a','a').mode,'unchanged');assert.equal(delta('abc','xyz').mode,'replace');});
test('agent mapping, observations, bounded history and disappeared pane cleanup',async()=>{const f=fake(),a=new Agents(f.backend);const s=await a.spawn({name:'worker',cli:'shell'});assert.equal(a.get('worker').paneId,7);const first=await a.observe(s.agentId);const second=await a.observe(s.agentId,first.observationId);assert.equal(second.recentText,'');assert.equal(second.activity,'unchanged');f.setText('$ hello');const third=await a.observe(s.agentId,second.observationId);assert.equal(third.outputMode,'append');for(let i=0;i<20;i++)await a.observe(s.agentId);assert.equal(a.get(s.agentId).history.length,16);assert.equal((await a.observe(s.agentId,first.observationId)).deltaReset,true);f.remove();await assert.rejects(a.observe(s.agentId),/disappeared/);assert.equal(a.records.size,0);});
test('silent output does not count as idle; waits time out; failed spawn retains recoverable mapping',async()=>{const f=fake();f.setText('long command with no output');const a=new Agents(f.backend);await assert.rejects(a.spawn({name:'worker',cli:'claude',prompt:'hello',timeoutMs:10}),/prompt NOT sent/);assert.equal(a.records.size,1);assert.equal((await a.observe('worker')).status,'UNKNOWN');assert.equal(f.calls.filter(c=>c.args[0]==='send-text').length,0);});
test('permission detection prevents automatic initial prompt submission',async()=>{const f=fake();f.setText('Do you trust this folder?\n❯ Yes');const a=new Agents(f.backend);await assert.rejects(a.spawn({name:'p',cli:'claude',prompt:'do work',timeoutMs:5}));assert.equal((await a.observe('p')).status,'WAITING_FOR_PERMISSION');});
test('state classifier examples',()=>{const fixtures:[string,string,string][]=[['claude','Claude Code\n❯ ','READY_FOR_PROMPT'],['claude','Thinking… (esc to interrupt)','WORKING'],['claude','Do you want to proceed?\n❯ 1. Yes','WAITING_FOR_PERMISSION'],['codex','OpenAI Codex\n› Explain this codebase','READY_FOR_PROMPT'],['codex','Working (4s • esc to interrupt)','WORKING'],['codex','Choose an option\nEnter to select','WAITING_FOR_QUESTION'],['claude','API Error: invalid token','ERROR'],['shell','running silently','UNKNOWN']];for(const [cli,text,status] of fixtures)assert.equal(adapters[cli].classify(text),status);});
test('subprocess timeout and execution errors are diagnostic',async()=>{await assert.rejects(execute(process.execPath,['-e','setTimeout(()=>{},10000)'],undefined,20),/timed out/);await assert.rejects(execute('/nonexistent/term-dad',[]),/Check executable/);});

test('captured Claude UI fixture recognizes prompt despite non-blocking local hook error',async()=>{const {readFile}=await import('node:fs/promises');const text=await readFile(new URL('./fixtures/claude-ready.txt',import.meta.url),'utf8');assert.equal(adapters.claude.classify(text),'READY_FOR_PROMPT');});

test('captured Codex UI fixture recognizes the current interactive prompt',async()=>{const {readFile}=await import('node:fs/promises');const text=await readFile(new URL('./fixtures/codex-ready.txt',import.meta.url),'utf8');assert.equal(adapters.codex.classify(text),'READY_FOR_PROMPT');});
test('concurrent spawns reserve names before backend completion',async()=>{const f=fake(),a=new Agents(f.backend);const first=a.spawn({name:'same',cli:'shell'});await assert.rejects(a.spawn({name:'same',cli:'shell'}),/already exists/);await first;});
test('unchanged pre-input prompt does not become ready merely because time passes',async()=>{const f=fake(),a=new Agents(f.backend);await a.spawn({name:'worker',cli:'shell'});await a.send('worker','hello');a.get('worker').lastInputAt=Date.now()-2000;assert.equal((await a.observe('worker')).status,'WORKING');});
